# Generated by Django 2.1.3 on 2019-06-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='linkt',
            new_name='link',
        ),
    ]
